export enum ApiPaths {
  user = '/user',
  userLogin = '/login',

  tour = '/tour',
  tourdetails = '/GetById?id=',
  tourUpcoming = '/Upcoming',
  tourPast = '/Past',
  tourCategories = "/categories",

  tourguide = '/TourGuide',
  tgUpcomingTours = '/UpcomingTours',
  tgPastTours = '/PastTours',
  tgReviews = '/Reviews',
  tourCard = '/CardDetails',
  tourDet = '/tourDet',
  createtour = '/',
  admin = "/admin",
  adminTour = "/Tour",
  adminTourRequest = "/Request",
  adminTourguide = "/TourGuide",
  adminTGApplicant = "/Applicant",
  custReg = "/CustomerRegistration",
  tgReg = "/TourGuideRegistration",
}
